version: '3.12'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
      SECRET_KEY: mysecretkey
      FLASK_APP: app.py
    ports:
      - "8081:8080"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
