LATEX_FILE = proj5
LATEX = pdflatex

all:
	$(LATEX) $(LATEX_FILE).tex
	$(LATEX) $(LATEX_FILE).tex
	$(LATEX) $(LATEX_FILE).tex

clean:
	rm -f $(LATEX_FILE).aux $(LATEX_FILE).log $(LATEX_FILE).out $(LATEX_FILE).toc $(LATEX_FILE).fls $(LATEX_FILE).fdb_latexmk

.PHONY: all clean
